<a href="https://colab.research.google.com/github/sabinasiraj/data-sciencelab/blob/main/prgm1_to_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np
array_from_list=np.array([1,2,3,4,5])
print("Array from list:",array_from_list)
array_with_range=np.arange(10)
print("array with range",array_with_range)
zeros_array=np.zeros((3,3))
print("zeros array",zeros_array)
ones_array=np.ones((2,5))
print("ones array",ones_array)

Array from list: [1 2 3 4 5]
array with range [0 1 2 3 4 5 6 7 8 9]
zeros array [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones array [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [4]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
add_result=np.add(a,b)
print("Addition:",add_result)
sub_result=np.subtract(a,b)
print("Subtraction:",sub_result)
mul_result=np.multiply(a,b)
print("Multiplication:",mul_result)
div_result=np.divide(a,b)
print("Division:",div_result)


Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


In [15]:
import numpy as np
array = np.arange(12)
print("Original array:",array)
reshaped_array = array.reshape(3, 4)
print("Reshaped to 3x4 array:",reshaped_array)
reshaped_array_3d = array.reshape((2,3,2))
print("Reshaped to 2x3x2:\n",reshaped_array)


Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to 3x4 array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped to 2x3x2:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [17]:
import numpy as np

array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

print("2D array:\n", array_2d)

element = array_2d[1, 2]
print("Element at (1,2):", element)

subarray = array_2d[1:3, 0:2]
print("Subarray:\n", subarray)

column = array_2d[:, 1]
print("Column 2:", column)

2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at (1,2): 6
Subarray:
 [[4 5]
 [7 8]]
Column 2: [2 5 8]


In [18]:
import numpy as np

# Creating an array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Calculating mean
mean = np.mean(array)
print("Mean:", mean)

# Calculating median
median = np.median(array)
print("Median:", median)

# Calculating standard deviation
std_dev = np.std(array)
print("Standard Deviation:", std_dev)

# Finding minimum and maximum values
min_val = np.min(array)
max_val = np.max(array)

print("Minimum value:", min_val)
print("Maximum value:", max_val)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Minimum value: 1
Maximum value: 10
